### PR TITLE
fix: update domain event attachment creation to use feature_id for slack url of AutoOpsRule and ProgressiveRollout

### LINKED ISSUE #1192: fix: slack notification url path for auto operation is broken
```
Environment: production
Entity ID: c5ee70fa-8c46-4d16-abc0-8cb5418fa937
URL: https://ENDPOINT/production/features/c5ee70fa-8c46-4d16-abc0-8cb5418fa937/settings
```

### PR DESCRIPTION
**Pull request by nnnkkk7**
fix #1192 

The ID in the URL must be the Flag ID, not the auto operation ID for AutoOpsRule and ProgressiveRollout.

### CODE REVIEW

File: pkg/notification/sender/notifier/slack.go [hunk 1]
```diff
@@ -189,11 +190,25 @@ func (n *slackNotifier) createDomainEventAttachment(
 ) (*slack.Attachment, error) {
 	// handle loc if multi-lang is necessary
 	localizedMessage := domainevent.LocalizedMessage(notification.Type, localizer)
+
+	ID := notification.EntityId
```
Comment (cre8ivejp) [inline pkg/notification/sender/notifier/slack.go:194]: WDYT?

```suggestion
	id := notification.EntityId
```
or
```suggestion
	entityID := notification.EntityId
```

Comment (nnnkkk7) [reply pkg/notification/sender/notifier/slack.go]: ok!
I fixed it!
[fix: rename variable](https://github.com/bucketeer-io/bucketeer/pull/1688/commits/69e3265d93e8ce2724ee9d0ad3adce58d3d4ec8f)

**Review by cre8ivejp — APPROVED** [review]
Nice 🎉
